# Generated by Django 2.1.2 on 2018-10-30 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='electronicpart',
            name='part_ptr',
        ),
        migrations.RemoveField(
            model_name='hardwarepart',
            name='part_ptr',
        ),
        migrations.RemoveField(
            model_name='product',
            name='parts',
        ),
        migrations.RenameField(
            model_name='part',
            old_name='name',
            new_name='location',
        ),
        migrations.DeleteModel(
            name='ElectronicPart',
        ),
        migrations.DeleteModel(
            name='HardwarePart',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
