# Generated by Django 2.1.2 on 2018-11-02 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_genericpart'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResistorPart',
            fields=[
                ('part_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventory.Part')),
                ('location', models.CharField(max_length=15)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('inventory.part',),
        ),
    ]
