# Generated by Django 2.1.2 on 2018-11-13 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_resistorpart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.RenameField(
            model_name='resistorpart',
            old_name='location',
            new_name='package',
        ),
        migrations.AddField(
            model_name='part',
            name='location',
            field=models.ManyToManyField(to='inventory.Location'),
        ),
    ]
