# Generated by Django 2.1.2 on 2018-10-30 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20181029_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='name',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
