# Generated by Django 2.1.2 on 2018-10-31 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_part_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='inStock',
        ),
        migrations.RemoveField(
            model_name='part',
            name='inventoryNumber',
        ),
        migrations.RemoveField(
            model_name='part',
            name='location',
        ),
        migrations.RemoveField(
            model_name='part',
            name='package',
        ),
    ]
